sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ljh111111
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7HibPoA7MVCb3u3sVK
    access-key-secret: S3hevU0ed31ijBz5etDQCKZG88TSnx
    bucket-name: lojh-sky-take-out
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  wechat:
    appid: wxd86c43b00cdd5117
    secret: 044b8780e203fd5682d0918d000d4e6f